import { useLocation, useNavigate } from "react-router-dom";
import { useEffect, useState } from "react";
import {
  Typography,
  Container,
  Button,
  Card,
  CardContent,
  CircularProgress,
  Box,
  Grid,
  Chip,
  CardMedia,
} from "@mui/material";
import { motion } from "framer-motion";

export default function Dashboard() {
  const location = useLocation();
  const navigate = useNavigate();
  const productURL = location.state?.productURL;

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [result, setResult] = useState(null);
  const [preview, setPreview] = useState(null);
  const [typedText, setTypedText] = useState("");
  const fullText = "Summary generated by AI 🤖";

  // typing animation
  useEffect(() => {
    let i = 0;
    const timer = setInterval(() => {
      if (i < fullText.length) {
        setTypedText((prev) => prev + fullText.charAt(i));
        i++;
      } else clearInterval(timer);
    }, 100);
    return () => clearInterval(timer);
  }, []);

  // analyze product
  useEffect(() => {
    if (!productURL) return;

    const analyzeProduct = async () => {
      try {
        const response = await fetch("http://127.0.0.1:5000/analyze", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ product_url: productURL }),
        });

        const data = await response.json();
        if (response.ok) setResult(data);
        else setError(data.error || "Something went wrong");
      } catch (err) {
        setError("Unable to connect to backend");
      } finally {
        setLoading(false);
      }
    };

    const fetchPreview = async () => {
      try {
        const response = await fetch(
          `https://api.linkpreview.net/?key=AIzaSyAuQpNQLPB0u8jjo5OJwU7rhNpMrfI2hX8&q=${encodeURIComponent(
            productURL
          )}`
        );
        const data = await response.json();
        setPreview(data);
      } catch {
        setPreview(null);
      }
    };

    analyzeProduct();
    fetchPreview();
  }, [productURL]);

  const renderSentimentBar = (sentiments) => {
    const total =
      sentiments.positive + sentiments.neutral + sentiments.negative;
    const positiveWidth = (sentiments.positive / total) * 100;
    const neutralWidth = (sentiments.neutral / total) * 100;
    const negativeWidth = (sentiments.negative / total) * 100;

    return (
      <Box
        sx={{
          display: "flex",
          height: 20,
          borderRadius: "10px",
          overflow: "hidden",
          mt: 1,
          mb: 2,
          boxShadow: "inset 0 0 5px rgba(0,0,0,0.1)",
        }}
      >
        <Box sx={{ width: `${positiveWidth}%`, backgroundColor: "#4caf50" }} />
        <Box sx={{ width: `${neutralWidth}%`, backgroundColor: "#ffeb3b" }} />
        <Box sx={{ width: `${negativeWidth}%`, backgroundColor: "#f44336" }} />
      </Box>
    );
  };

  return (
    <Box
      sx={{
        minHeight: "100vh",
        background: "linear-gradient(135deg, #e0f7fa 0%, #f3e5f5 100%)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        py: 6,
      }}
    >
      <Container>
        <Typography
          variant="h4"
          sx={{
            fontWeight: "bold",
            mb: 2,
            textAlign: "center",
            color: "#333",
          }}
        >
          Review Analysis Dashboard
        </Typography>

        {/* Product Preview Section */}
        <Card
          sx={{
            backgroundColor: "#ffffff",
            borderRadius: "20px",
            boxShadow: "0 0 20px rgba(63,81,181,0.15)",
            mb: 4,
            overflow: "hidden",
          }}
        >
          {preview ? (
            <Box sx={{ display: "flex", flexDirection: "row", p: 2 }}>
              {preview.image && (
                <CardMedia
                  component="img"
                  src={preview.image}
                  alt={preview.title}
                  sx={{
                    width: 150,
                    height: 150,
                    borderRadius: "12px",
                    objectFit: "cover",
                    mr: 2,
                  }}
                />
              )}
              <Box>
                <Typography variant="h6">{preview.title}</Typography>
                <Typography
                  variant="body2"
                  sx={{ color: "gray", mb: 1, maxWidth: "400px" }}
                >
                  {preview.description}
                </Typography>
                <Button
                  variant="outlined"
                  color="primary"
                  href={preview.url}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  View Product
                </Button>
              </Box>
            </Box>
          ) : (
            <Box sx={{ p: 2, textAlign: "center" }}>
              <Typography variant="body2">
                <strong>Product URL:</strong>{" "}
                <a href={productURL} target="_blank" rel="noopener noreferrer">
                  {productURL}
                </a>
              </Typography>
            </Box>
          )}
        </Card>

        {loading ? (
          <Box textAlign="center" mt={5}>
            <CircularProgress />
            <Typography variant="body2" sx={{ mt: 2 }}>
              Analyzing reviews...
            </Typography>
          </Box>
        ) : error ? (
          <Typography color="error" sx={{ textAlign: "center", mt: 3 }}>
            {error}
          </Typography>
        ) : (
          result && (
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.5 }}
            >
              <Card
                sx={{
                  backgroundColor: "#ffffff",
                  borderRadius: "20px",
                  mt: 3,
                  p: 3,
                  boxShadow:
                    "0 0 20px rgba(63,81,181,0.2), 0 0 40px rgba(156,39,176,0.1)",
                }}
              >
                <CardContent>
                  <Typography
                    variant="h6"
                    sx={{
                      fontWeight: "bold",
                      mb: 1,
                      color: "#3f51b5",
                      textAlign: "center",
                    }}
                  >
                    {typedText}
                  </Typography>

                  <Typography variant="body1" sx={{ mb: 3, textAlign: "center" }}>
                    {result.summary}
                  </Typography>

                  <Grid container spacing={2}>
                    <Grid item xs={12} sm={6}>
                      <Typography variant="body1">
                        <strong>Tone:</strong> {result.tone}
                      </Typography>
                      <Typography variant="body1">
                        <strong>Rating:</strong> ⭐ {result.rating}/5
                      </Typography>

                      <Typography variant="body1" sx={{ mt: 2 }}>
                        <strong>Sentiment Breakdown:</strong>
                      </Typography>
                      {renderSentimentBar(result.sentiment_breakdown)}
                      <Typography variant="body2">
                        Positive: {result.sentiment_breakdown.positive}% | Neutral:{" "}
                        {result.sentiment_breakdown.neutral}% | Negative:{" "}
                        {result.sentiment_breakdown.negative}%
                      </Typography>
                    </Grid>

                    <Grid item xs={12} sm={6}>
                      <Typography
                        variant="body1"
                        sx={{ fontWeight: "bold", mb: 1 }}
                      >
                        Pros:
                      </Typography>
                      {result.pros.map((p, i) => (
                        <Chip
                          key={i}
                          label={p}
                          color="success"
                          variant="outlined"
                          sx={{ mr: 1, mb: 1 }}
                        />
                      ))}

                      <Typography
                        variant="body1"
                        sx={{ fontWeight: "bold", mt: 2, mb: 1 }}
                      >
                        Cons:
                      </Typography>
                      {result.cons.map((c, i) => (
                        <Chip
                          key={i}
                          label={c}
                          color="error"
                          variant="outlined"
                          sx={{ mr: 1, mb: 1 }}
                        />
                      ))}
                    </Grid>
                  </Grid>

                  <Typography
                    variant="body2"
                    sx={{
                      mt: 3,
                      textAlign: "right",
                      fontStyle: "italic",
                      color: "#555",
                    }}
                  >
                    Based on {result.review_count} reviews analyzed.
                  </Typography>
                </CardContent>
              </Card>
            </motion.div>
          )
        )}

        <Box textAlign="center" mt={4}>
          <Button variant="outlined" onClick={() => navigate("/")}>
            Back
          </Button>
        </Box>
      </Container>
    </Box>
  );
}
